name = "keywords-frontend"
compatibility_date = "2024-09-10"

# Pages 配置
pages_build_output_dir = "dist"

# 环境变量配置
[vars]
NODE_ENV = "production"

# 开发环境配置
[env.preview]
name = "keywords-frontend-preview"
vars = { NODE_ENV = "development" }
