name = "keywords-api"
main = "src/index.js"
compatibility_date = "2024-09-10"
compatibility_flags = ["nodejs_compat"]

# KV 命名空间绑定
[[kv_namespaces]]
binding = "KEYWORDS_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# 环境变量
[vars]
ENVIRONMENT = "production"

# 开发环境配置
[env.dev]
name = "keywords-api-dev"
vars = { ENVIRONMENT = "development" }

# 路由配置
[[routes]]
pattern = "your-domain.com/api/*"
zone_name = "your-domain.com"
