name = "keywords-api"
main = "src/index.js"
compatibility_date = "2024-09-10"
compatibility_flags = ["nodejs_compat"]

# KV 命名空间绑定
[[kv_namespaces]]
binding = "KEYWORDS_KV"
id = "f360d59dfc2948fe948c93ee4004d4a8"
preview_id = "c7efa7429a244e2b976c73887650d511"

# 环境变量
[vars]
ENVIRONMENT = "production"

# 开发环境配置
[env.dev]
name = "keywords-api-dev"
vars = { ENVIRONMENT = "development" }


